version: 2.1

orbs:
  ruby: circleci/ruby@2.0.0

jobs:
  build:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - ruby/install:
          version: '2.7.6'
      - run: echo "Ruby 2.7.6 has been installed"
      - ruby/install-deps
  checking:
    docker:
      - image: 'cimg/ruby:2.7-node'
    steps:
      - checkout
      - ruby/install-deps
      - ruby/rubocop-check:
          format: progress
          label: Inspecting with Rubocop
  test:
    docker:
      - image: 'cimg/ruby:2.7-node'
      - environment:
          POSTGRES_DB: spire_test
          POSTGRES_PASSWORD: ''
          POSTGRES_USER: spire-user
        image: 'circleci/postgres:9.5-alpine'
    environment:
      BUNDLE_JOBS: '3'
      BUNDLE_RETRY: '3'
      PGHOST: 127.0.0.1
      PGPASSWORD: ''
      PGUSER: spire-user
      RAILS_ENV: test
    parallelism: 3
    steps:
      - checkout
      - ruby/install:
          version: '2.7.6'
      - ruby/install-deps
      - ruby/rspec-test:
          include: spec/features/*.rb
workflows:
  build_and_check:
    jobs:
      - build
      - checking
      - test:
          requires:
            - build