# AWS Build Specification

version: 0.2

env:
  variables:
    NODE_OPTIONS: '--max-old-space-size=14336'

# Define the commands that occur at each phase of the automated build process. This maps directly to the
# phases within the AWS CodeBuild console.  See
# https://us-east-2.console.aws.amazon.com/codebuild/home?region=us-east-2#/projects

phases:
  # The INSTALL phase installs Ruby test
  install:
    commands:
      - APP_DIR=`pwd`
      - echo `pwd`
      - env
      - |
          GIT_BRANCH="$(git symbolic-ref HEAD --short 2>/dev/null)"
          if [ "$GIT_BRANCH" = "" ] ; then
            GIT_BRANCH="$(git rev-parse HEAD | xargs git name-rev | cut -d' ' -f2 | sed 's/remotes\/origin\///g')";
          fi
          - echo GIT_BRANCH - $GIT_BRANCH
      - echo $GIT_BRANCH
      - echo `pwd`

  # The BUILD phase
  build:
    commands:
      - echo `Build Phase`

  # The POST BUILD phase - Wrapped all suite executions in a retry statment
  post_build:
    commands:
      - ERROR=0
      - exit $ERROR